# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfc643f0411f7e4875511acd4c089241aa877e14a0b4af0f7e69291206c923f1ad64e4d26deb5fd542b960a8d78301bc9fb3579e7c978b09e804231f4f43fa04

test:
  secret_key_base: 68a9bae3a37ed4035e6d6682a3b60396505b3a96bb3aaf01315c8a0134e9a3ca77257892a6de523350347467f5e936ca13552538602f58d29fac8dc80afca283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
